kelo_platform_controller_gz:
  ros__parameters:
    base_control_mode: VELOCITY
    wheels_controller: base_velocity_controller
    num_wheels: 4
    
    platform_max_lin_vel: 0.5
    platform_max_ang_vel: 1.0

    pivot_joint_identifier: pivot_joint

    wheels:
      wheel0:
        identifier: front_left
        x: 0.195
        y: 0.21
        a: 0.0

      wheel1:
        identifier: rear_left
        x: -0.195
        y: 0.21
        a: 0.0

      wheel2:
        identifier: rear_right
        x: -0.195
        y: -0.21
        a: 0.0

      wheel3:
        identifier: front_right
        x: 0.195
        y: -0.21
        a: 0.0